# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4dx_EibMKvpmicWVkO_dkAkukr3XwcO
"""

import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np

datos = []
x = []

for y in range(480):
    x.append(y+1)

with open("CANAL_ROJO.txt") as archivo:
    for linea in archivo:
        datos.append(int(linea))


plt.hist(datos, bins = 255, color = "red", rwidth=1)
plt.title("CANAL: ROJO")
plt.xlabel("INTENSIDAD DE COLOR")
plt.ylabel("CANTIDAD DE PIXELES")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np

datos = []
x = []

for y in range(480):
    x.append(y+1)

with open("CANAL_VERDE.txt") as archivo:
    for linea in archivo:
        datos.append(int(linea))


plt.hist(datos, bins = 255, color = "lime", rwidth=1)
plt.title("CANAL: VERDE")
plt.xlabel("INTENSIDAD DE COLOR")
plt.ylabel("CANTIDAD DE PIXELES")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np

datos = []
x = []

for y in range(480):
    x.append(y+1)

with open("CANAL_AZUL.txt") as archivo:
    for linea in archivo:
        datos.append(int(linea))


plt.hist(datos, bins = 255, color = "blue", rwidth=1)
plt.title("CANAL: AZUL")
plt.xlabel("INTENSIDAD DE COLOR")
plt.ylabel("CANTIDAD DE PIXELES")
plt.show()